theme: jekyll-theme-cayman

title: Talebaatil Kulliyaatul Mumenaat Toronto
description: [Official website for the Organization of Talebaatil Kulliyaatul Mumenaat Toronto]

future: true
timezone: TIMEZONE
