theme: jekyll-theme-cayman

title: [Talebaat-ul-Kulliyatul Mumenaat Toronto]
description: [Main website for the Organization of Talebaat-ul-Kulliyatul Mumenaat Toronto]

show_downloads: true
google_analytics: [Talebaat Toronto]

future: true
timezone: TIMEZONE
